// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/accrual/accrual.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// CreateResponseLog mocks base method.
func (m *Mocklogger) CreateResponseLog(statusCode int, large int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateResponseLog", statusCode, large)
}

// CreateResponseLog indicates an expected call of CreateResponseLog.
func (mr *MockloggerMockRecorder) CreateResponseLog(statusCode, large interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResponseLog", reflect.TypeOf((*Mocklogger)(nil).CreateResponseLog), statusCode, large)
}
